# This workflow build the Docker image with the application 

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the container application
  build_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # For cross-platform
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker image with Buildx and specify arm64 architecture
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: arm64
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ghcr.io/${{ github.actor }}/tflite_example:latest

      # Upload artifact
      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: ghcr.io/${{ github.actor }}/tflite_example:latest

