# This is workflow tests the application from the Docker image

name: Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Run the application
  run_app:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Download artifact
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: |
          docker pull ghcr.io/${{ github.actor }}/tflite_example:latest

      # Run application
      - name: Run application
        run: |
          docker run --rm ghcr.io/${{ github.actor }}/tflite_example:latest | tee app.out

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: app.out

  # Test the application output
  test_app:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: run_app

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Download shell2junit
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: manolo/shell2junit

      - name: Download output
        uses: actions/download-artifact@v3
        with:
          name: output

      - name: Unit tests
        run: |
          . sh2ju.sh
          juLogClean
          check_output () { # $1-string
            #check if $1 is found in output.log
            if grep -q "${1}"; output.log; then
              return 0
            else
              return 1
            fi
          }
          juLog -name="military uniform" check_output "0.919721: 653:military uniform"
          juLog -name="windsor tie" check_output "0.017762: 907:Windsor tie"
          juLog -name="mortarboard" check_output "0.007507: 668:mortarboard"
          juLog -name="bulletproof vest" check_output "0.005419: 466:bulletproof vest"
          juLog -name="bow tie" check_output "0.003828: 458:bow tie, bow-tie, bowtie"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/results/TEST-*.xml'

